services:
  talent-bridge:
    container_name: talent-bridgecontainer
    build: .
    image: talent-bridge:v1

    ports:
      - "80:80"

    expose:
      - "80"

    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge